import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/StoreProvider";
import React from "react";
import Counter from "./components/atoms/Button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Buena Mascota",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Counter />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
