name: Deploy Project
on:
  push:
    branches:
      - 'main'
jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run jest test
        run: yarn test
      - name: Start server
        run: yarn start &
        env:
          CI: true
      - name: Run cypress test
        run: yarn cypress:run
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: build project
        run: yarn build
      - name: Deploy
        run: echo "deploying..."
